-- Cost Control & Usage Limiting Schema
-- Date: 2025-12-18

-- 1. Create usage_logs table
CREATE TABLE IF NOT EXISTS public.usage_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID REFERENCES public.organizations(id) ON DELETE CASCADE NOT NULL,
    feature_name TEXT NOT NULL, -- 'chat', 'summarize', etc.
    model_used TEXT NOT NULL, -- 'gpt-4o', 'gpt-4o-mini'
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    estimated_cost_usd NUMERIC(10, 6) NOT NULL DEFAULT 0, -- Store with high precision (e.g., 0.000123)
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Index for fast aggregation (Summing costs per org per month)
CREATE INDEX IF NOT EXISTS idx_usage_logs_org_date ON public.usage_logs(organization_id, created_at);

-- RLS for usage_logs
ALTER TABLE public.usage_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Org members view own usage logs" ON public.usage_logs
    FOR SELECT
    USING (
        organization_id IN (
            SELECT organization_id FROM profiles WHERE id = auth.uid()
        )
    );

-- System (Service Role) can insert logs. 
-- No user insert policy needed as logs are generated by backend logic.


-- 2. Update plan_limits table
-- Add columns for limits if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'plan_limits' AND column_name = 'max_monthly_cost_usd') THEN
        ALTER TABLE public.plan_limits ADD COLUMN max_monthly_cost_usd NUMERIC(10, 2);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'plan_limits' AND column_name = 'allowed_models') THEN
        ALTER TABLE public.plan_limits ADD COLUMN allowed_models TEXT[];
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'plan_limits' AND column_name = 'max_file_upload_size_mb') THEN
        ALTER TABLE public.plan_limits ADD COLUMN max_file_upload_size_mb INTEGER;
    END IF;
END $$;


-- 3. Seed Plan Limits Data (Update existing rows)
-- FREE Plan
UPDATE public.plan_limits
SET 
    max_monthly_cost_usd = 1.00,  -- Very low limit for free tier
    allowed_models = ARRAY['gpt-4o-mini'],
    max_file_upload_size_mb = 5
WHERE plan_id = 'FREE';

-- STANDARD Plan (Target: 2000 JPY/mo ~= $13 USD. Cost limit 15% = $2.00)
UPDATE public.plan_limits
SET 
    max_monthly_cost_usd = 2.00,
    allowed_models = ARRAY['gpt-4o-mini'], -- Standard users stuck on mini per logic req
    max_file_upload_size_mb = 20
WHERE plan_id = 'STANDARD';

-- PRO Plan (Target: ?? JPY/mo. High limit)
UPDATE public.plan_limits
SET 
    max_monthly_cost_usd = 20.00, -- Fair usage cap
    allowed_models = ARRAY['gpt-4o', 'gpt-4o-mini'],
    max_file_upload_size_mb = 100
WHERE plan_id = 'PRO';

-- ENTERPRISE Plan
UPDATE public.plan_limits
SET 
    max_monthly_cost_usd = 100.00,
    allowed_models = ARRAY['gpt-4o', 'gpt-4o-mini', 'o1-preview'],
    max_file_upload_size_mb = 500
WHERE plan_id = 'ENTERPRISE';
