-- Phase 1: Core Tables Setup
-- Generated by Agent for "Phase 1 - Assets & Database Core Setup"

-- A. Organizations (Tenant)
CREATE TABLE IF NOT EXISTS public.organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('social_welfare', 'npo', 'medical_corp')),
    plan TEXT NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'standard', 'pro')),
    stripe_customer_id TEXT,
    current_period_end TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for organizations
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

-- B. Assistant Profiles
CREATE TABLE IF NOT EXISTS public.assistant_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE CHECK (code IN ('aoi', 'aki', 'ami')),
    name TEXT NOT NULL,
    avatar_url TEXT DEFAULT '/assets/avatars/aoi_face_icon.jpg',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for assistant_profiles
ALTER TABLE public.assistant_profiles ENABLE ROW LEVEL SECURITY;

-- C. Officers (Governance)
CREATE TABLE IF NOT EXISTS public.officers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    term_end DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for officers
ALTER TABLE public.officers ENABLE ROW LEVEL SECURITY;

-- Add RLS Policies (Basic)
-- Note: These are idempotent policy creations
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'organizations' AND policyname = 'Users can view their own organization') THEN
        CREATE POLICY "Users can view their own organization" ON public.organizations
            FOR SELECT USING (auth.uid() IN (
                SELECT id FROM profiles WHERE organization_id = organizations.id
            ));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'assistant_profiles' AND policyname = 'Everyone can view assistant profiles') THEN
        CREATE POLICY "Everyone can view assistant profiles" ON public.assistant_profiles
            FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'officers' AND policyname = 'Users can view their organization officers') THEN
        CREATE POLICY "Users can view their organization officers" ON public.officers
            FOR SELECT USING (organization_id IN (
                SELECT organization_id FROM profiles WHERE id = auth.uid()
            ));
    END IF;
END $$;
