-- Phase 2: Business Logic & Automation
-- Generated by Agent for "Phase 2 - Business Logic & Automation"

-- 1. Enable pg_cron (Scheduled Tasks)
CREATE EXTENSION IF NOT EXISTS pg_cron;
GRANT USAGE ON SCHEMA cron TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA cron TO postgres;

-- 2. Plan Limits (Feature Gating)
CREATE TABLE IF NOT EXISTS public.plan_limits (
    plan_id TEXT PRIMARY KEY CHECK (plan_id IN ('free', 'standard', 'pro', 'enterprise')),
    max_members INTEGER NOT NULL DEFAULT 1,
    storage_limit_gb INTEGER NOT NULL DEFAULT 1,
    features JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.plan_limits ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read plan limits (for UI display)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'plan_limits' AND policyname = 'Public read access to plan_limits') THEN
        CREATE POLICY "Public read access to plan_limits" ON public.plan_limits
            FOR SELECT USING (true);
    END IF;
END $$;

-- Seed Plan Limits Data
INSERT INTO public.plan_limits (plan_id, max_members, storage_limit_gb, features)
VALUES 
    ('free', 1, 1, '{
        "email_sending": false,
        "word_export": false,
        "audit_logs": false,
        "custom_domain": false,
        "priority_support": false
    }'::jsonb),
    ('standard', 5, 10, '{
        "email_sending": true,
        "word_export": false,
        "audit_logs": false,
        "custom_domain": false,
        "priority_support": false
    }'::jsonb),
    ('pro', 20, 50, '{
        "email_sending": true,
        "word_export": true,
        "audit_logs": true,
        "custom_domain": false,
        "priority_support": true
    }'::jsonb),
    ('enterprise', 9999, 1000, '{
        "email_sending": true,
        "word_export": true,
        "audit_logs": true,
        "custom_domain": true,
        "priority_support": true
    }'::jsonb)
ON CONFLICT (plan_id) DO UPDATE
SET 
    max_members = EXCLUDED.max_members,
    storage_limit_gb = EXCLUDED.storage_limit_gb,
    features = EXCLUDED.features;

-- 3. Automations (Example: Monthly Usage Reset)
-- Schedule a job to run on the 1st of every month at 00:00 UTC
-- Note: Requires pg_cron to be active in the database
SELECT cron.schedule(
    'reset_monthly_usage',
    '0 0 1 * *',
    $$
    -- Placeholder for usage reset logic
    -- UPDATE usage_logs SET ... 
    SELECT 1; 
    $$
);
